//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobtab
    {
        public int jobid { get; set; }
        public int companyid { get; set; }
        public string jobname { get; set; }
        public int vaccancy { get; set; }
        public string description { get; set; }
        public string salary { get; set; }
        public string skill { get; set; }
        public string qualification { get; set; }
        public string date { get; set; }
        public string status { get; set; }
    }
}
